# ============= CONFIGURATION MYSQL =============
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:mysql://localhost:3306/DIGITAL_WEB_VIEW
#spring.datasource.username=root
#spring.datasource.password=root
##

spring.datasource.url=jdbc:mysql://localhost:3306/trx
spring.datasource.username=root
spring.datasource.password=ba-MysqL-m-$-i-2024!Secure-s-
#

#spring.datasource.url=jdbc:mysql://172.24.1.20:3306/trx
#spring.datasource.username=ddhh
#spring.datasource.password=ddhh


# Datasource MySQL (primary)



# ============= CONFIGURATION JPA/HIBERNATE =============
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============= CONFIGURATION DU SERVEUR =============
server.port=8077
server.servlet.context-path=/banking_access


app.upload.dir=C:/Users/DOP/Documents/TestUpload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB



# ============= CONFIGURATION DE POOL DE CONNEXIONS =============
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000



# ============= CONFIGURATION GENERALE =============
spring.application.name=banking_access
spring.main.allow-bean-definition-overriding=true

